site_name: Cybersecurity do Zero
site_description: Aprenda Cybersecurity do Zero entendendo os fundamentos antes das ferramentas.
site_author: Willian Hirata
site_url: https://willianhirata.github.io/cybersecurity-do-zero/

docs_dir: docs
site_dir: site

theme:
  name: material
  language: pt-BR
  custom_dir: overrides

  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Ativar modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Ativar modo claro

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - social

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables

  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Início: index.md

  - Fundamentos:
      - Visão Geral: fundamentos/index.md
      - O que é Cybersecurity?: fundamentos/001-o-que-e-cybersecurity.md
      - A Tríade CIA: fundamentos/002-triade-cia.md

  - Redes:
      - Visão Geral: redes/index.md

  - Linux:
      - Visão Geral: linux/index.md

  - Windows:
      - Visão Geral: windows/index.md

  - Blue Team:
      - Visão Geral: blue-team/index.md

  - OSINT:
      - Visão Geral: osint/index.md

  - Threat Intelligence:
      - Visão Geral: threat-intelligence/index.md

  - Laboratórios:
      - Visão Geral: laboratorios/index.md
