site_name: Cybersecurity do Zero
site_description: Aprenda Cybersecurity do Zero entendendo os fundamentos antes das ferramentas.
site_author: Willian Hirata
site_url: https://willianhirata.github.io/cybersecurity-do-zero/

theme:
  name: material

  language: pt-BR

  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Ativar modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Ativar modo claro

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

  extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Início: index.md

  - Fundamentos:
      - Visão geral: fundamentos/index.md
      - O que é Cybersecurity?: fundamentos/o-que-e-cybersecurity.md

  - Redes:
      - Visão geral: redes/index.md

  - Linux:
      - Visão geral: linux/index.md

  - Windows:
      - Visão geral: windows/index.md

  - Blue Team:
      - Visão geral: blue-team/index.md

  - OSINT:
      - Visão geral: osint/index.md

  - Threat Intelligence:
      - Visão geral: threat-intelligence/index.md

  - Laboratórios:
      - Visão geral: laboratorios/index.md
